Add support for parentLocales
camertron/ruby-cldr pull request #3
Opened 2016-11-26 05:02 UTC by natemueller

Use the parentLocales section to figure out the correct fallback locales.  The new test passes when I unpack a modern CLDR in vendor/cldr.  I wasn't sure what the proper test procedure is but that worked so I went with it.  Let me know if I should change anything.

2016-11-27 20:39 UTC, camertron requested changes
A few comments, but nothing major. Looks good overall, thanks for the PR.

That said, would you mind targeting the original repo (svenfuchs/ruby-cldr) instead of my fork? That's still the official ruby-cldr repo.

2016-11-27 20:39 UTC, camertron commented on lib/cldr/export/data/parent_locales.rb
> +          path = "#{Cldr::Export::Data.dir}/supplemental/supplementalData.xml"
Maybe go with a `File.join` here?

2016-11-27 20:39 UTC, camertron commented on lib/cldr/export.rb
> +        to_i18n = lambda {|l| l.to_s.gsub('_', '-').to_sym }
This is cool, but why not make it a method instead of a lambda?

2016-11-27 20:39 UTC, camertron commented on lib/cldr/export/data/parent_locales.rb
> +          currency_digits_and_rounding = doc.xpath('//parentLocales/parentLocale').each do |node|
Copy/paste artifact? 😛

2016-11-27 20:46 UTC, natemueller commented
Sure, easy changes.  I targeted this one because it's what the twitter-cldr-rb's Gemfile uses.  If I submit these to svenfuchs should I also change switch twitter-cldr-rb to use that version?

2016-11-28 16:14 UTC, camertron commented on lib/cldr/download.rb
> +      source ||= 'http://unicode.org/Public/cldr/26/core.zip'
This is fine, just FYI that twitter-cldr-rb targets CLDR v29.

2016-11-28 16:16 UTC, camertron approved these changes

2016-11-28 16:16 UTC, camertron commented on lib/cldr/export.rb
> +          ancestory = [locale]
Spelling: "ancestry"

2016-11-28 16:17 UTC, camertron commented
Just a couple of other minor comments. Not sure why the fields stuff is showing up in this diff either. Will investigate.

2016-11-28 16:19 UTC, natemueller commented
I rebased my change onto svenfuchs/ruby-cldr master, so it updated the PR to include one of your earlier changes.  Thought I closed this one out.  Sorry about the confusion.

2016-11-28 16:19 UTC, closed without merging

2016-11-28 16:28 UTC, camertron commented
Got it, thanks. I'll merge the upstream changes when the svenfuchs PR gets merged.